### PR TITLE
Evaluator pair dlvo bug fix

### LINKED ISSUE #1142: File not included in hoomd/md/CMakeLists.txt
## Description

There appears to be a missing file in the _md_headers portion of the hoomd/md/CMakeLists.txt file.
I propose that the file "EvaluatorPairDLVO.h" be added so that it can be included externally from hoomd (i.e. in a plugin)

## Script

```C++
// From an external plugin:
#include <hoomd/md/EvaluatorPairDLVO.h>

```

```console
# From terminal, build folder within external plugin
cmake ..
cmake --build ../build/
```

## Output

fatal error:  hoomd/md/EvaluatorPairDLVO.h: No such file or directory

## Expected output

none (compile successfully)

## Configuration

Platform:
- Linux

Installation method:
- Compiled from source

Versions:
- Python version: 3.9
- **HOOMD-blue** version: 2.9

## Developer

I will submit a pull request fixing the issue.

### PR DESCRIPTION
**Pull request by NathanDavisBarrett**
## Description

There appears to be a missing file in the _md_headers portion of the hoomd/md/CMakeLists.txt file.
I propose that the file "EvaluatorPairDLVO.h" be added so that it can be included externally from hoomd (i.e. in a plugin)

This is because EvaluatorPairDLVO.h is not referenced in hoomd/md/CMakeLists.txt

I just added it in the appropriate place.

## Motivation and context

When trying to include the file hoomd/md/EvaluatorPairDLVO.h from an external plugin, the compiler throws an error since the file is not copied into the python module's "include" folder.

Adding a reference to the file allows for the file to be copied over to the python module at compile time and therefore enables it to be included by an external plugin.

Resolves #1142

## How has this been tested?

1. I added a reference to EvaluatorPairDLVO.h in the _md_headers section of hoomd/md/CMakeLists.txt
2. I compiled and install hoomd with this change.
3. I checked to make sure EvaluatorPairDLVO.h is in python3.9/site-packages/hoomd/include/hoomd/md (which it is, after the change)

## Change log

```
2021-09-21  Nathan Barrett  <ndb.nathan.barrett@gmail.com>

    * hoomd/md/CMakeLists.txt (_md_headers): added "EvaluatorPairDLVO.h"
    
    * sphinx-doc/credits.rst: added "Nathan Barrett, Pritzker School of Molecular Engineering"
```

## Checklist:

- [ x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x ] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x ] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

File: hoomd/md/TwoStepNVE.h [hunk 1]
```diff
@@ -19,7 +19,7 @@
 #include <pybind11/pybind11.h>
 
 //! Integrates part of the system forward in two steps in the NVE ensemble
-/*! Implements velocity-verlet NVE integration through the IntegrationMethodTwoStep interface
+/*! Implements velocity-verlet+ NVE integration through the IntegrationMethodTwoStep interface
```
Comment (joaander) [inline hoomd/md/TwoStepNVE.h:22]:
```suggestion
/*! Implements velocity-verlet NVE integration through the IntegrationMethodTwoStep interface
```

File: hoomd/md/integrate.py [hunk 2]
```diff
@@ -249,3 +249,137 @@ def _attach(self):
...
+
+        for i in range(len(self._forces)):
+            force = self._forces[i]
+            freq = self._forceFreqs[i]
+
+            self._cpp_obj.addForce(force, freq)
+
+        # Call attach from DynamicIntegrator which attaches forces,
+        # constraint_forces, and methods, and calls super()._attach() itself.
+        super()._attach()
```
Comment (joaander) [inline hoomd/md/integrate.py:385]:
```suggestion
```

**Review by joaander — CHANGES_REQUESTED** [review]
Please revert the irrelevant changes.

In the future, consider using `git add <file>` and `git commit` to commit only specific changes. 

I will squash merge this branch to simplify the history. Alternately, you could make a new branch with only commits 72c1394 and 6638c48 cherry-picked in it, then force push that branch here.

**Comment by NathanDavisBarrett** [comment]
Sorry about that, I was created the brach from the wrong point.
It should be good to go now.

**Review by joaander — APPROVED** [review]
Thanks!
