### PR TITLE
Initial changes to compile on AMD

### LINKED ISSUE #1101: Compatibility of HOOMD with the newest ROCm
Hi! Is there any information that HOOMD v3.0.0 beta 8 supports ROCm 4.3.0? The requirement [here](https://hoomd-blue.readthedocs.io/en/latest/building.html) says ROCm >= 3.5.0 but is it up-to-date?

While building HOOMD I get a lot of errors like:
`error: no matching function for call to ‘hip_impl::Scalar_accessor<double, double [4], 0>::Scalar_accessor(int)’`
that are similar (or maybe even the same) as  @jglaser pointed to here: https://github.com/ROCm-Developer-Tools/HIP/issues/1675

### PR DESCRIPTION
**Pull request by jglaser**
## Description

Make HOOMD compile on AMD architectures with HIP

Compiles, but not yet functional

## Motivation and context

Resolves #1101 

## Change log

```

```

## Checklist:

- [ ] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [ ] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [ ] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

File: hoomd/md/ForceComposite.h [hunk 1]
```diff
@@ -172,13 +172,13 @@ class PYBIND11_EXPORT ForceComposite : public MolecularForceCompute
...
-                                                     h_body_orientation.data[index].y,
-                                                     h_body_orientation.data[index].z,
-                                                     h_body_orientation.data[index].w));
+            positions.append(pybind11::make_tuple((Scalar)h_body_pos.data[index].x,
+                                                  (Scalar)h_body_pos.data[index].y,
+                                                  (Scalar)h_body_pos.data[index].z));
+            orientations.append(pybind11::make_tuple((Scalar)h_body_orientation.data[index].x,
+                                                     (Scalar)h_body_orientation.data[index].y,
+                                                     (Scalar)h_body_orientation.data[index].z,
+                                                     (Scalar)h_body_orientation.data[index].w));
```
Comment (b-butler) [inline hoomd/md/ForceComposite.h]: These changes are unrelated? Also we should use a `static_cast<Scalar>()` over C style casting.

File: hoomd/md/EvaluatorTersoff.h [hunk 2]
```diff
@@ -91,15 +91,15 @@ class EvaluatorTersoff
             pybind11::dict v;
 
             pybind11::list mags;
-            mags.append(coeffs.x);
-            mags.append(coeffs.y);
+            mags.append((Scalar)coeffs.x);
+            mags.append((Scalar)coeffs.y);
```
Comment (b-butler) [inline hoomd/md/EvaluatorTersoff.h]: Seems unrelated to AMD compilation. Also, use `static_cast`.

File: hoomd/md/EvaluatorTersoff.h [hunk 3]
```diff
@@ -91,15 +91,15 @@ class EvaluatorTersoff
...
             v["magnitudes"] = pybind11::tuple(mags);
 
             v["cutoff_thickness"] = cutoff_thickness;
 
             pybind11::list exp_factors;
-            exp_factors.append(exp_consts.x);
-            exp_factors.append(exp_consts.y);
+            exp_factors.append((Scalar)exp_consts.x);
+            exp_factors.append((Scalar)exp_consts.y);
```
Comment (b-butler) [inline hoomd/md/EvaluatorTersoff.h]: See comment above.

**Review by b-butler — COMMENTED** [review]
There are many seemingly unrelated casts, as well as many places where code is commented rather than removed.

File: hoomd/md/EvaluatorTersoff.h (hunk 2 above)
Comment (joaander) [reply hoomd/md/EvaluatorTersoff.h]: If I recall correctly, AMD's HIP uses non-standard types for `float4` and `double4` (and `Scalar4` by proxy) - so this may be necessary. @jglaser can confirm.

File: hoomd/md/ForceComposite.h (hunk 1 above)
Comment (jglaser) [reply hoomd/md/ForceComposite.h]: HIP uses a proxy class for vector data types, which does not always cast automatically to the underlying data type.  Changing to `static_cast<>()`

**Comment by jglaser** [comment]
> There are many seemingly unrelated casts, as well as many places where code is commented rather than removed.

removed the obsolete commented code for now, which pertained to external library depencies such as hipsparse (for cusparse). Will have to see if unit tests complete for the distance constraint force in this case, and if not, we can add back any needed rocM dependencies later.

**Comment by jglaser** [comment]
Can this be merged? Do you need me to address any more comments?

File: hoomd/md/OPLSDihedralForceCompute.cc [hunk 4]
```diff
@@ -323,22 +323,22 @@ void OPLSDihedralForceCompute::computeForces(uint64_t timestep)
...
+        h_force.data[i2].z = h_force.data[i2].z + f2.z;
+        h_force.data[i2].w = h_force.data[i2].w + f2.w;
+        h_force.data[i3].x = h_force.data[i3].x + f3.x;
+        h_force.data[i3].y = h_force.data[i3].y + f3.y;
+        h_force.data[i3].z = h_force.data[i3].z + f3.z;
+        h_force.data[i3].w = h_force.data[i3].w + f3.w;
+        h_force.data[i4].x = h_force.data[i4].x + f4.x;
+        h_force.data[i4].y = h_force.data[i4].y + f4.y;
+        h_force.data[i4].z = h_force.data[i4].z + f4.z;
+        h_force.data[i4].w = h_force.data[i4].z + f4.w;
```
Comment (joaander) [inline hoomd/md/OPLSDihedralForceCompute.cc]:
```suggestion
        h_force.data[i4].w = h_force.data[i4].w + f4.w;
```

**Review by joaander — CHANGES_REQUESTED** [review]
Thanks Jens! I like the nice clean CMake code.

The OPLS unit test is failing. I hope my suggested change fixes the test. Aside from that, are there any updates needed to the documentation on HIP support?

File: hoomd/md/OPLSDihedralForceCompute.cc (hunk 4 above)
Comment (jglaser) [reply hoomd/md/OPLSDihedralForceCompute.cc]: good catch! I thought I had looked over this part of the code more than once and didn't spot it... :)

**Comment by jglaser** [comment]
> Thanks Jens! I like the nice clean CMake code.
> 
> The OPLS unit test is failing. I hope my suggested change fixes the test. Aside from that, are there any updates needed to the documentation on HIP support?

We might have to document/enforce the minimum CMake version for HIP language support (3.21).
https://cmake.org/cmake/help/latest/command/enable_language.html

And, only the MD module has been tested.

**Comment by joaander** [comment]
> > Thanks Jens! I like the nice clean CMake code.
> > The OPLS unit test is failing. I hope my suggested change fixes the test. Aside from that, are there any updates needed to the documentation on HIP support?
> 
> We might have to document/enforce the minimum CMake version for HIP language support (3.21). https://cmake.org/cmake/help/latest/command/enable_language.html

OK, let's do that. Does the ROCm minimum requirement also need updating?

> 
> And, only the MD module has been tested.

That's fine. This PR is just making the initial changes. We will do more testing in future work.

**Comment by joaander** [comment]
pre-commit.ci autofix

**Comment by joaander** [comment]
I added the CMake variable `HOOMD_GPU_PLATFORM` which lets the user choose between `CUDA` and `HIP`. Users may have HIP installed on a system but prefer to use the CUDA backend.

**Review by joaander — APPROVED** [review]
Thanks!

This is ready to merge with the final tweaks I made to the CMake scripts and documentation.

File: hoomd/md/BondTablePotential.cc [hunk 5]
```diff
@@ -128,8 +128,8 @@ pybind11::dict BondTablePotential::getParams(std::string type)
 
     auto type_id = m_bond_data->getTypeByName(type);
     pybind11::dict params;
-    params["r_min"] = h_params.data[type_id].x;
-    params["r_max"] = h_params.data[type_id].y;
+    params["r_min"] = (Scalar)h_params.data[type_id].x;
+    params["r_max"] = (Scalar)h_params.data[type_id].y;
```
Comment (b-butler) [inline hoomd/md/BondTablePotential.cc]:
```suggestion
    params["r_min"] = static_cast<Scalar>(h_params.data[type_id].x);
    params["r_max"] = static_cast<Scalar>(h_params.data[type_id].y);

```

File: CMake/hoomd/HOOMDHIPSetup.cmake [hunk 6]
```diff
@@ -110,31 +33,39 @@ int main(int argc, char **argv)
...
-                $<$<NOT:$<COMPILE_LANGUAGE:CUDA>>:__HIP_PLATFORM_HCC__>)
-        endif()
+#        # branch upon HCC or NVCC target
+#        if(${HIP_PLATFORM} STREQUAL "nvcc")
+#            set_property(TARGET HIP::hip APPEND PROPERTY INTERFACE_COMPILE_DEFINITIONS
+#                $<$<NOT:$<COMPILE_LANGUAGE:CUDA>>:__HIP_PLATFORM_NVCC__>)
+#        elseif(${HIP_PLATFORM} STREQUAL "hip-clang")
+#            set_property(TARGET HIP::hip APPEND PROPERTY INTERFACE_COMPILE_DEFINITIONS
+#                $<$<NOT:$<COMPILE_LANGUAGE:CUDA>>:__HIP_PLATFORM_HCC__>)
+#        endif()
```
Comment (b-butler) [inline CMake/hoomd/HOOMDHIPSetup.cmake]:
```suggestion
```
delete?

**Review by b-butler — CHANGES_REQUESTED** [review]
Just left a couple comments.

**Comment by joaander** [comment]
@b-butler Do you approve?

**Review by b-butler — APPROVED** [review]
