### PR TITLE
Fix and test pair energy shift

### LINKED ISSUE #1504: pair.mode = 'shift' is incorrect for `LJGauss`, `ExpandedMie`, `Fourier`, `ExpandedLJ`, and `TWF`
### Description

When setting `pair.mode = 'shift'`, these potentials either don't shift at all or provide incorrect shifts.

### Script

```python
# run in a jupyter notebook
import hoomd
import matplotlib, matplotlib.figure
import numpy
%matplotlib inline

snapshot = hoomd.Snapshot()
snapshot.particles.N = 2
snapshot.particles.position[:] = [[0, 0, 0], [0, 0, 0]]
snapshot.particles.types = ['A']
snapshot.configuration.box = [50, 50, 50]

sim = hoomd.Simulation(device=hoomd.device.CPU())
sim.create_state_from_snapshot(snapshot)

r_cut = 2
r_array = numpy.linspace(1.5, r_cut + 1, 500)
v_array = numpy.zeros_like(r_array)

potential = hoomd.md.pair.ExpandedLJ(nlist=hoomd.md.nlist.Cell(buffer=0.4))
potential.params[('A', 'A')] = dict(sigma=1.0, epsilon=1.5, delta=0.5)
potential.r_cut[('A', 'A')] = r_cut
potential.mode='shift'
sim.operations.computes.append(potential)
sim.run(0)

for i,r in enumerate(r_array):
    snapshot.particles.position[1] = [r, 0, 0]
    sim.state.set_snapshot(snapshot)
    
    v_array[i] = potential.energy

fig = matplotlib.figure.Figure(figsize=(10, 6.18))
ax = fig.add_subplot()
ax.plot(r_array, v_array)
ax.set_xlabel('r')
ax.set_ylabel('V')
fig
```

### Input files

_No response_

### Output

image

### Expected output

I expect a potential that goes to 0 as `r` approaches `r_cut` from the left.

### Platform

CPU, GPU, Linux, macOS

### Installation method

Compiled from source

### HOOMD-blue version

3.9.0

### Python version

3.11.2

### PR DESCRIPTION
**Pull request by joaander**
## Description

* Fix the energy shift calculations in `ExpandedLJ`, `ExpandedMie`, `LJGauss`, and `TWF`. Document that `Fourier` does not support the mode `"shift"`.
* Fix some inaccuracies in the pair force documentation.

## Motivation and context

These potentials did not shift V(r_cut) to 0. 

Resolves #1504 

## How has this been tested?

I added a unit test checking that all pair potentials shift V(r_cut) to 0.

## Change log

```
Fixed:

* The pair potentials `ExpandedLJ`, `ExpandedMie`, `LJGauss`, and `TWF` now shift `V(r_cut)` to 0.
* Corrected errors in the pair potential documentation.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

File: hoomd/md/EvaluatorPairExpandedLJ.h [hunk 1]
```diff
@@ -180,8 +178,12 @@ class EvaluatorPairExpandedLJ
...
                 {
-                Scalar rcut2inv = rcutinv * rcutinv;
-                Scalar rcut6inv = rcut2inv * rcut2inv * rcut2inv;
+                Scalar rcut = fast::sqrt(rcutsq);
+                Scalar r_cut_shifted = rcut - delta;
+                Scalar r_cut_shifted_inv = Scalar(1.0) / r_cut_shifted;
+
+                Scalar r_cut2inv = r_cut_shifted_inv * r_cut_shifted_inv;
+                Scalar rcut6inv = r_cut2inv * r_cut2inv * r_cut2inv;
                 pair_eng -= rcut6inv * (lj1 * rcut6inv - lj2);
```
Comment (b-butler) [inline hoomd/md/EvaluatorPairExpandedLJ.h]:
```suggestion
                Scalar r_cut = fast::sqrt(rcutsq);
                Scalar r_cut_shifted = r_cut - delta;
                Scalar r_cut_shifted_inv = Scalar(1.0) / r_cut_shifted;

                Scalar r_cut2_inv = r_cut_shifted_inv * r_cut_shifted_inv;
                Scalar r_cut6_inv = r_cut2_inv * r_cut2_inv * r_cut2_inv;
                pair_eng -= r_cut6_inv * (lj1 * r_cut6_inv - lj2);
```
Consistent (and more) underscoring

File: hoomd/md/EvaluatorPairExpandedMie.h [hunk 2]
```diff
@@ -189,8 +189,11 @@ class EvaluatorPairExpandedMie
...
             if (energy_shift)
                 {
-                Scalar rcutninv = fast::pow(rcutsq, -n_pow / Scalar(2.0));
-                Scalar rcutminv = fast::pow(rcutsq, -m_pow / Scalar(2.0));
+                Scalar rcut = fast::sqrt(rcutsq);
+                Scalar r_cut_shifted = rcut - delta;
+
+                Scalar rcutninv = fast::pow(r_cut_shifted, -n_pow);
+                Scalar rcutminv = fast::pow(r_cut_shifted, -m_pow);
                 pair_eng -= repulsive * rcutninv - attractive * rcutminv;
```
Comment (b-butler) [inline hoomd/md/EvaluatorPairExpandedMie.h]:
```suggestion
                Scalar r_cut = fast::sqrt(rcutsq);
                Scalar r_cut_shifted = r_cut - delta;

                Scalar r_cut_n_inv = fast::pow(r_cut_shifted, -n_pow);
                Scalar r_cut_m_inv = fast::pow(r_cut_shifted, -m_pow);
                pair_eng -= repulsive * r_cut_n_inv - attractive * r_cut_m_inv;
```
Consistent and more underlining.

**Review by b-butler — COMMENTED** [review]
Two small comments but otherwise, nice fix.
