### PR TITLE
Fix/dump sphero shapes without vertices

### LINKED ISSUE #600: Seg fault on dumping convexspheropolyhedron shape with implicit depletants
## Description

When dumping to a gsd file in a system with hpmc convex sphero-polyhedral particles and implicit spherical depletants, a segmentation fault occurs when a call to hoomd.dump.gsd.dump_shape is made. This error does not occur when the sphere or convexpolyhedron integrators are used, but I have not tested other integrators. The error does not occur if the call to dump_shape is not made.  

## Script

```python
import hoomd
from hoomd import hpmc

particle_vertices = [[-0.5,-0.5,-0.5], [0.5,0.5,-0.5],
                    [0.5,-0.5,-0.5], [-0.5,0.5,-0.5],
                    [-0.5,-0.5,0.5], [0.5,0.5,0.5],
                    [0.5,-0.5,0.5], [-0.5,0.5,0.5]]

hoomd.context.initialize("")
system = hoomd.init.create_lattice(hoomd.lattice.sc(a=1, type_name='A'), n=[5,5,5])
system.particles.types.add("B")
mc = hpmc.integrate.convex_spheropolyhedron(seed=1234, implicit=True, depletant_mode='circumsphere')
mc.set_params(nselect=8,nR=3,depletant_type='B')  
mc.shape_param.set('A', vertices=particle_vertices, sweep_radius=0)
mc.shape_param.set('B', vertices=[], sweep_radius=0.1)

dump = hoomd.dump.gsd(filename='test.gsd', group=hoomd.group.all(), period=10, phase=0, overwrite=False)
dump.dump_state(mc)
dump.dump_shape(mc)

hoomd.run_upto(100)

```

## Output

HOOMD-blue v2.9.0-3-gdf7970121 DOUBLE HPMC_MIXED MPI SSE SSE2 
Compiled: 02/26/2020
Copyright (c) 2009-2019 The Regents of the University of Michigan.
-----
You are using HOOMD-blue. Please cite the following:
* J A Anderson, C D Lorenz, and A Travesset. "General purpose molecular dynamics
  simulations fully implemented on graphics processing units", Journal of
  Computational Physics 227 (2008) 5342--5359
* J Glaser, T D Nguyen, J A Anderson, P Lui, F Spiga, J A Millan, D C Morse, and
  S C Glotzer. "Strong scaling of general-purpose molecular dynamics simulations
  on GPUs", Computer Physics Communications 192 (2015) 97--107
-----
-----
You are using HPMC. Please cite the following:
* J A Anderson, M E Irrgang, and S C Glotzer. "Scalable Metropolis Monte Carlo
  for simulation of hard shapes", Computer Physics Communications 204 (2016) 21
  --30
-----
HOOMD-blue is running on the CPU
segfault.py:010  |  system = hoomd.init.create_lattice(hoomd.lattice.sc(a=1, type_name='A'), n=[5,5,5])
segfault.py:010  |  system = hoomd.init.create_lattice(hoomd.lattice.sc(a=1, type_name='A'), n=[5,5,5])
notice(2): Group "all" created containing 125 particles
segfault.py:012  |  mc = hpmc.integrate.convex_spheropolyhedron(seed=1234, implicit=True, depletant_mode='circumsphere')
-----
You are using implicit depletants. Please cite the following:
* J Glaser, A S Karas, and S C Glotzer. "A parallel algorithm for implicit
  depletant simulations", The Journal of Chemical Physics 143 (2015) 184110
-----
segfault.py:013  |  mc.set_params(nselect=8,nR=3,depletant_type='B')  
segfault.py:017  |  dump = hoomd.dump.gsd(filename='test.gsd', group=hoomd.group.all(), period=10, phase=0, overwrite=False)
segfault.py:017  |  dump = hoomd.dump.gsd(filename='test.gsd', group=hoomd.group.all(), period=10, phase=0, overwrite=False)
** starting run **
[dali:848397] *** Process received signal ***
[dali:848397] Signal: Segmentation fault (11)
[dali:848397] Signal code: Address not mapped (1)
[dali:848397] Failing at address: (nil)
[dali:848397] [ 0] /usr/lib/libc.so.6(+0x3bfb0)[0x7fe831ca7fb0]
[dali:848397] [ 1] /nfs/turbo/bi-vislab/plawton/hoomd-blue/build/hoomd/hpmc/_hpmc.cpython-38-x86_64-linux-gnu.so(+0x63d377)[0x7fe826f79377]
[dali:848397] [ 2] /nfs/turbo/bi-vislab/plawton/hoomd-blue/build/hoomd/hpmc/_hpmc.cpython-38-x86_64-linux-gnu.so(+0x63d9f9)[0x7fe826f799f9]
[dali:848397] [ 3] /nfs/turbo/bi-vislab/plawton/hoomd-blue/build/hoomd/_hoomd.cpython-38-x86_64-linux-gnu.so(_ZN13GSDDumpWriter7analyzeEj+0x4ed)[0x7fe830eb819d]
[dali:848397] [ 4] /nfs/turbo/bi-vislab/plawton/hoomd-blue/build/hoomd/_hoomd.cpython-38-x86_64-linux-gnu.so(_ZN6System3runEjjN8pybind116objectEdj+0xf26)[0x7fe830fab1c6]
[dali:848397] [ 5] /nfs/turbo/bi-vislab/plawton/hoomd-blue/build/hoomd/_hoomd.cpython-38-x86_64-linux-gnu.so(+0x3335ce)[0x7fe830fb45ce]
[dali:848397] [ 6] /nfs/turbo/bi-vislab/plawton/hoomd-blue/build/hoomd/_hoomd.cpython-38-x86_64-linux-gnu.so(+0xa8a0c)[0x7fe830d29a0c]
[dali:848397] [ 7] /usr/lib/libpython3.8.so.1.0(PyCFunction_Call+0x66)[0x7fe831a28cc6]
[dali:848397] [ 8] /usr/lib/libpython3.8.so.1.0(_PyObject_MakeTpCall+0x442)[0x7fe8319e3ad2]
[dali:848397] [ 9] /usr/lib/libpython3.8.so.1.0(+0xfd5d6)[0x7fe8319aa5d6]
[dali:848397] [10] /usr/lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x4ad8)[0x7fe831aa03c8]
[dali:848397] [11] /usr/lib/libpython3.8.so.1.0(_PyEval_EvalCodeWithName+0x3cb)[0x7fe831a88e3b]
[dali:848397] [12] /usr/lib/libpython3.8.so.1.0(_PyFunction_Vectorcall+0x39b)[0x7fe831a8a24b]
[dali:848397] [13] /usr/lib/libpython3.8.so.1.0(PyObject_Call+0x1ed)[0x7fe8319db30d]
[dali:848397] [14] /usr/lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x2413)[0x7fe831a9dd03]
[dali:848397] [15] /usr/lib/libpython3.8.so.1.0(_PyEval_EvalCodeWithName+0x3cb)[0x7fe831a88e3b]
[dali:848397] [16] /usr/lib/libpython3.8.so.1.0(_PyFunction_Vectorcall+0x39b)[0x7fe831a8a24b]
[dali:848397] [17] /usr/lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x4ad8)[0x7fe831aa03c8]
[dali:848397] [18] /usr/lib/libpython3.8.so.1.0(_PyEval_EvalCodeWithName+0x3cb)[0x7fe831a88e3b]
[dali:848397] [19] /usr/lib/libpython3.8.so.1.0(PyEval_EvalCode+0x23)[0x7fe831b123d3]
[dali:848397] [20] /usr/lib/libpython3.8.so.1.0(+0x265428)[0x7fe831b12428]
[dali:848397] [21] /usr/lib/libpython3.8.so.1.0(+0x269623)[0x7fe831b16623]
[dali:848397] [22] /usr/lib/libpython3.8.so.1.0(PyRun_FileExFlags+0x97)[0x7fe8319b13e7]
[dali:848397] [23] /usr/lib/libpython3.8.so.1.0(PyRun_SimpleFileExFlags+0x390)[0x7fe8319bbf4a]
[dali:848397] [24] /usr/lib/libpython3.8.so.1.0(Py_RunMain+0x4fe)[0x7fe831b238be]
[dali:848397] [25] /usr/lib/libpython3.8.so.1.0(Py_BytesMain+0x39)[0x7fe831b239a9]
[dali:848397] [26] /usr/lib/libc.so.6(__libc_start_main+0xf3)[0x7fe831c93153]
[dali:848397] [27] python(_start+0x2e)[0x5653274b005e]
[dali:848397] *** End of error message ***
Segmentation fault (core dumped)

## Expected output

Normal hoomd hpmc output.

## Configuration

Small system of cubes with implicit spherical depletants.

Platform:
- Linux
- CPU

Installation method:
- Compiled from source

Versions:
- Python version: 3.8.1
- **HOOMD-blue** version: 2.9.0

## Developer

I would have to look into it more, and would like to help, but I am pretty confident someone else will know what to do much faster than I will be able to figure it out.

### PR DESCRIPTION
**Pull request by vyasr**
## Description

Ensure that spheropolygons and spheropolyhedra have at least 1 vertex when dumped.

## Motivation and context

Resolves #600 

## How has this been tested?

This was verified manually on a HOOMD 2.x script, but hasn't been tested in v3. If a test is desired I'd appreciate if someone else could write it.

## Change log

```
Fix segmentation fault that occurred when dumping GSD shapes for spheropolygons and spheropolyhedra with no vertices (discs and spheres respectively).
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

File: hoomd/hpmc/ShapeConvexPolygon.h [hunk 1]
```diff
@@ -601,11 +601,18 @@ inline std::string getShapeSpec(const ShapeConvexPolygon& poly)
     {
     std::ostringstream shapedef;
     shapedef << "{\"type\": \"Polygon\", \"rounding_radius\": " << poly.verts.sweep_radius << ", \"vertices\": [";
-    for (unsigned int i = 0; i < poly.verts.N-1; i++)
+    if (verts.N != 0)
         {
-        shapedef << "[" << poly.verts.x[i] << ", " << poly.verts.y[i] << "], ";
+        for (unsigned int i = 0; i < poly.verts.N-1; i++)
```
Comment (bdice) [inline hoomd/hpmc/ShapeConvexPolygon.h:606]: There is some inconsistency between `verts` and `poly.verts`. We probably want the shorter form? I also see below that the other diff defines `auto& verts = poly.verts;` but I don’t see that snippet here. Also that should be const.

**Review by bdice — CHANGES_REQUESTED** [review]
See comment.

File: hoomd/hpmc/ShapeConvexPolygon.h (hunk 1 above)
Comment (vyasr) [reply hoomd/hpmc/ShapeConvexPolygon.h:606]: Good catch, I had only done the polyhedron version then decided to port to the polygon before making this PR.

**Review by bdice — APPROVED** [review]
LGTM

**Review by joaander — APPROVED** [review]
Thanks! Is there a need to backport these fixes to the 2.9 branch?
