### PR TITLE
Fix MPCD autotuners

### LINKED ISSUE #1937: `Operations.is_tuning_complete` does not consider MPCD objects
### Description

This property does not consider if tuning is complete on MPCD objects because they are held by `mpcd.Integrator` and not the standard list of operations. Similarly to how `md.Integrator` handles this for methods, `mpcd::Integator::isAutotuningComplete` needs to be extended to include the tuning of these objects.

### Script

```python
N/A
```

### Input files

_No response_

### Output

```shell
N/A
```

### Expected output

_No response_

### Platform

Linux

### Installation method

Compiled from source

### HOOMD-blue version

4.9.1

### Python version

3.13.0

### PR DESCRIPTION
**Pull request by mphoward**
## Description

This PR makes autotuned MPCD objects check if objects they own are also autotuned, as well as restarting tuning on those objects. This wasn't done previously, so completion of tuning could potentially have been marked as completed sooner than it was done. Since the `Integrator` is the entry point for all of these checks, `Operations.is_tuning_complete` should now work correctly because it checks the integrator explicitly.

This PR also makes consistent usage of the `override` keyword, which I noted while implementing this.

## Motivation and context

Resolves #1937 

## How has this been tested?

I will setup a GPU simulation and make sure `is_tuning_complete` initially reports `False`. It originally reported `True` for a pure MPCD simulation (incorrect).

## Checklist:

- [X] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [X] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [X] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.
- [x] I have summarized these changes in `CHANGELOG.rst` following the established format.

### CODE REVIEW

File: hoomd/mpcd/ATCollisionMethodGPU.h [hunk 1]
```diff
@@ -34,10 +34,10 @@ class PYBIND11_EXPORT ATCollisionMethodGPU : public mpcd::ATCollisionMethod
 
     protected:
     //! Draw velocities for particles in each cell on the GPU
-    virtual void drawVelocities(uint64_t timestep);
+    virtual void drawVelocities(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/ATCollisionMethodGPU.h]:
```suggestion
    void drawVelocities(uint64_t timestep) override;
```
I don't run clang-tidy on hoomd, but it would tell us to use `override` instead of `virtual`. It is the modern way (tm).

File: hoomd/mpcd/ATCollisionMethodGPU.h [hunk 2]
```diff
@@ -34,10 +34,10 @@ class PYBIND11_EXPORT ATCollisionMethodGPU : public mpcd::ATCollisionMethod
...
 
     //! Apply the random velocities to particles in each cell on the GPU
-    virtual void applyVelocities();
+    virtual void applyVelocities() override;
```
Comment (joaander) [inline hoomd/mpcd/ATCollisionMethodGPU.h]:
```suggestion
    void applyVelocities() override;
```

File: hoomd/mpcd/BounceBackNVE.h [hunk 3]
```diff
@@ -46,10 +46,10 @@ class PYBIND11_EXPORT BounceBackNVE : public hoomd::md::IntegrationMethodTwoStep
     virtual ~BounceBackNVE();
 
     //! Performs the first step of the integration
-    virtual void integrateStepOne(uint64_t timestep);
+    virtual void integrateStepOne(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/BounceBackNVE.h]:
```suggestion
    void integrateStepOne(uint64_t timestep) override;
```

File: hoomd/mpcd/BounceBackNVE.h [hunk 4]
```diff
@@ -46,10 +46,10 @@ class PYBIND11_EXPORT BounceBackNVE : public hoomd::md::IntegrationMethodTwoStep
...
 
     //! Performs the second step of the integration
-    virtual void integrateStepTwo(uint64_t timestep);
+    virtual void integrateStepTwo(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/BounceBackNVE.h]:
```suggestion
    void integrateStepTwo(uint64_t timestep) override;
```

File: hoomd/mpcd/BounceBackNVEGPU.h [hunk 5]
```diff
@@ -44,10 +44,10 @@ template<class Geometry> class PYBIND11_EXPORT BounceBackNVEGPU : public BounceB
         }
 
     //! Performs the first step of the integration
-    virtual void integrateStepOne(uint64_t timestep);
+    virtual void integrateStepOne(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/BounceBackNVEGPU.h]:
```suggestion
    void integrateStepOne(uint64_t timestep) override;
```

File: hoomd/mpcd/BounceBackNVEGPU.h [hunk 6]
```diff
@@ -44,10 +44,10 @@ template<class Geometry> class PYBIND11_EXPORT BounceBackNVEGPU : public BounceB
...
 
     //! Performs the second step of the integration
-    virtual void integrateStepTwo(uint64_t timestep);
+    virtual void integrateStepTwo(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/BounceBackNVEGPU.h]:
```suggestion
    void integrateStepTwo(uint64_t timestep) override;
```

File: hoomd/mpcd/BounceBackStreamingMethod.h [hunk 7]
```diff
@@ -63,7 +63,7 @@ class PYBIND11_EXPORT BounceBackStreamingMethod : public mpcd::StreamingMethod
         }
 
     //! Implementation of the streaming rule
-    virtual void stream(uint64_t timestep);
+    virtual void stream(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/BounceBackStreamingMethod.h]:
```suggestion
    void stream(uint64_t timestep) override;
```

File: hoomd/mpcd/BounceBackStreamingMethodGPU.h [hunk 8]
```diff
@@ -60,7 +60,7 @@ class PYBIND11_EXPORT BounceBackStreamingMethodGPU
         }
 
     //! Implementation of the streaming rule
-    virtual void stream(uint64_t timestep);
+    virtual void stream(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/BounceBackStreamingMethodGPU.h]:
```suggestion
    void stream(uint64_t timestep) override;
```

File: hoomd/mpcd/CellListGPU.h [hunk 9]
```diff
@@ -31,7 +31,7 @@ class PYBIND11_EXPORT CellListGPU : public mpcd::CellList
 
     protected:
     //! Compute the cell list of particles on the GPU
-    virtual void buildCellList();
+    virtual void buildCellList() override;
```
Comment (joaander) [inline hoomd/mpcd/CellListGPU.h]:
```suggestion
    void buildCellList() override;
```

File: hoomd/mpcd/CellThermoComputeGPU.h [hunk 10]
```diff
@@ -39,17 +39,17 @@ class PYBIND11_EXPORT CellThermoComputeGPU : public mpcd::CellThermoCompute
     protected:
 #ifdef ENABLE_MPI
     //! Begin the calculation of outer cell properties on the GPU
-    virtual void beginOuterCellProperties();
+    virtual void beginOuterCellProperties() override;
```
Comment (joaander) [inline hoomd/mpcd/CellThermoComputeGPU.h]:
```suggestion
    void beginOuterCellProperties() override;
```

File: hoomd/mpcd/CellThermoComputeGPU.h [hunk 11]
```diff
@@ -39,17 +39,17 @@ class PYBIND11_EXPORT CellThermoComputeGPU : public mpcd::CellThermoCompute
...
 
     //! Finish the calculation of outer cell properties on the GPU
-    virtual void finishOuterCellProperties();
+    virtual void finishOuterCellProperties() override;
```
Comment (joaander) [inline hoomd/mpcd/CellThermoComputeGPU.h]:
```suggestion
    void finishOuterCellProperties() override;
```

File: hoomd/mpcd/CellThermoComputeGPU.h [hunk 12]
```diff
@@ -39,17 +39,17 @@ class PYBIND11_EXPORT CellThermoComputeGPU : public mpcd::CellThermoCompute
...
 #endif // ENABLE_MPI
 
     //! Calculate the inner cell properties on the GPU
-    virtual void calcInnerCellProperties();
+    virtual void calcInnerCellProperties() override;
```
Comment (joaander) [inline hoomd/mpcd/CellThermoComputeGPU.h]:
```suggestion
    void calcInnerCellProperties() override;
```

File: hoomd/mpcd/CellThermoComputeGPU.h [hunk 13]
```diff
@@ -39,17 +39,17 @@ class PYBIND11_EXPORT CellThermoComputeGPU : public mpcd::CellThermoCompute
...
 
     //! Compute the net properties from the cell properties
-    virtual void computeNetProperties();
+    virtual void computeNetProperties() override;
```
Comment (joaander) [inline hoomd/mpcd/CellThermoComputeGPU.h]:
```suggestion
    void computeNetProperties() override;
```

File: hoomd/mpcd/CommunicatorGPU.h [hunk 14]
```diff
@@ -57,7 +57,7 @@ class PYBIND11_EXPORT CommunicatorGPU : public mpcd::Communicator
     //@{
 
     //! Migrate particle data to local domain
-    virtual void migrateParticles(uint64_t timestep);
+    virtual void migrateParticles(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/CommunicatorGPU.h]:
```suggestion
    void migrateParticles(uint64_t timestep) override;
```

File: hoomd/mpcd/CommunicatorGPU.h [hunk 15]
```diff
@@ -71,7 +71,7 @@ class PYBIND11_EXPORT CommunicatorGPU : public mpcd::Communicator
 
     protected:
     //! Set the communication flags for the particle data on the GPU
-    virtual void setCommFlags(const BoxDim& box);
+    virtual void setCommFlags(const BoxDim& box) override;
```
Comment (joaander) [inline hoomd/mpcd/CommunicatorGPU.h]:
```suggestion
    void setCommFlags(const BoxDim& box) override;
```

File: hoomd/mpcd/Integrator.h [hunk 16]
```diff
@@ -40,13 +40,19 @@ class PYBIND11_EXPORT Integrator : public hoomd::md::IntegratorTwoStep
     virtual ~Integrator();
 
     //! Take one timestep forward
-    virtual void update(uint64_t timestep);
+    virtual void update(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/Integrator.h]:
```suggestion
    void update(uint64_t timestep) override;
```

File: hoomd/mpcd/Integrator.h [hunk 17]
```diff
@@ -40,13 +40,19 @@ class PYBIND11_EXPORT Integrator : public hoomd::md::IntegratorTwoStep
...
 
     //! Change the timestep
-    virtual void setDeltaT(Scalar deltaT);
+    virtual void setDeltaT(Scalar deltaT) override;
```
Comment (joaander) [inline hoomd/mpcd/Integrator.h]:
```suggestion
    void setDeltaT(Scalar deltaT) override;
```

File: hoomd/mpcd/Integrator.h [hunk 18]
```diff
@@ -40,13 +40,19 @@ class PYBIND11_EXPORT Integrator : public hoomd::md::IntegratorTwoStep
...
 
     //! Prepare for the run
-    virtual void prepRun(uint64_t timestep);
+    virtual void prepRun(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/Integrator.h]:
```suggestion
    void prepRun(uint64_t timestep) override;
```

File: hoomd/mpcd/ParallelPlateGeometryFiller.h [hunk 19]
```diff
@@ -56,10 +56,10 @@ class PYBIND11_EXPORT ParallelPlateGeometryFiller : public mpcd::ManualVirtualPa
     unsigned int m_N_hi; //!< number of particles to fill above channel
 
     //! Compute the total number of particles to fill
-    virtual void computeNumFill();
+    virtual void computeNumFill() override;
```
Comment (joaander) [inline hoomd/mpcd/ParallelPlateGeometryFiller.h]:
```suggestion
    void computeNumFill() override;
```

File: hoomd/mpcd/ParallelPlateGeometryFiller.h [hunk 20]
```diff
@@ -56,10 +56,10 @@ class PYBIND11_EXPORT ParallelPlateGeometryFiller : public mpcd::ManualVirtualPa
...
 
     //! Draw particles within the fill volume
-    virtual void drawParticles(uint64_t timestep);
+    virtual void drawParticles(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/ParallelPlateGeometryFiller.h]:
```suggestion
    void drawParticles(uint64_t timestep) override;
```

File: hoomd/mpcd/ParallelPlateGeometryFillerGPU.h [hunk 21]
```diff
@@ -34,7 +34,7 @@ class PYBIND11_EXPORT ParallelPlateGeometryFillerGPU : public mpcd::ParallelPlat
 
     protected:
     //! Draw particles within the fill volume on the GPU
-    virtual void drawParticles(uint64_t timestep);
+    virtual void drawParticles(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/ParallelPlateGeometryFillerGPU.h]:
```suggestion
    void drawParticles(uint64_t timestep) override;
```

File: hoomd/mpcd/PlanarPoreGeometryFiller.h [hunk 22]
```diff
@@ -58,10 +58,10 @@ class PYBIND11_EXPORT PlanarPoreGeometryFiller : public mpcd::ManualVirtualParti
     GPUArray<uint2> m_ranges;                //!< Particle tag ranges for filling
 
     //! Compute the total number of particles to fill
-    virtual void computeNumFill();
+    virtual void computeNumFill() override;
```
Comment (joaander) [inline hoomd/mpcd/PlanarPoreGeometryFiller.h]:
```suggestion
    void computeNumFill() override;
```

File: hoomd/mpcd/PlanarPoreGeometryFiller.h [hunk 23]
```diff
@@ -58,10 +58,10 @@ class PYBIND11_EXPORT PlanarPoreGeometryFiller : public mpcd::ManualVirtualParti
...
 
     //! Draw particles within the fill volume
-    virtual void drawParticles(uint64_t timestep);
+    virtual void drawParticles(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/PlanarPoreGeometryFiller.h]:
```suggestion
    void drawParticles(uint64_t timestep) override;
```

File: hoomd/mpcd/PlanarPoreGeometryFillerGPU.h [hunk 24]
```diff
@@ -34,7 +34,7 @@ class PYBIND11_EXPORT PlanarPoreGeometryFillerGPU : public mpcd::PlanarPoreGeome
 
     protected:
     //! Draw particles within the fill volume on the GPU
-    virtual void drawParticles(uint64_t timestep);
+    virtual void drawParticles(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/PlanarPoreGeometryFillerGPU.h]:
```suggestion
    void drawParticles(uint64_t timestep) override;
```

File: hoomd/mpcd/RejectionVirtualParticleFiller.h [hunk 25]
```diff
@@ -70,7 +70,7 @@ class PYBIND11_EXPORT RejectionVirtualParticleFiller : public mpcd::VirtualParti
         }
 
     //! Fill the particles outside the confinement
-    virtual void fill(uint64_t timestep);
+    virtual void fill(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/RejectionVirtualParticleFiller.h]:
```suggestion
    void fill(uint64_t timestep) override;
```

File: hoomd/mpcd/RejectionVirtualParticleFillerGPU.h [hunk 26]
```diff
@@ -54,7 +54,7 @@ class PYBIND11_EXPORT RejectionVirtualParticleFillerGPU
 
     protected:
     //! Fill the volume outside the confinement
-    virtual void fill(uint64_t timestep);
+    virtual void fill(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/RejectionVirtualParticleFillerGPU.h]:
```suggestion
    void fill(uint64_t timestep) override;
```

File: hoomd/mpcd/SRDCollisionMethod.h [hunk 27]
```diff
@@ -95,7 +101,7 @@ class PYBIND11_EXPORT SRDCollisionMethod : public mpcd::CollisionMethod
     GPUVector<double> m_factors;  //!< Cell-level rescale factors
 
     //! Implementation of the collision rule
-    virtual void rule(uint64_t timestep);
+    virtual void rule(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/SRDCollisionMethod.h]:
```suggestion
    void rule(uint64_t timestep) override;
```

File: hoomd/mpcd/SRDCollisionMethodGPU.h [hunk 28]
```diff
@@ -34,10 +34,10 @@ class PYBIND11_EXPORT SRDCollisionMethodGPU : public mpcd::SRDCollisionMethod
 
     protected:
     //! Randomly draw cell rotation vectors
-    virtual void drawRotationVectors(uint64_t timestep);
+    virtual void drawRotationVectors(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/SRDCollisionMethodGPU.h]:
```suggestion
    void drawRotationVectors(uint64_t timestep) override;
```

File: hoomd/mpcd/SRDCollisionMethodGPU.h [hunk 29]
```diff
@@ -34,10 +34,10 @@ class PYBIND11_EXPORT SRDCollisionMethodGPU : public mpcd::SRDCollisionMethod
...
 
     //! Apply rotation matrix to velocities
-    virtual void rotate(uint64_t timestep);
+    virtual void rotate(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/SRDCollisionMethodGPU.h]:
```suggestion
    void rotate(uint64_t timestep) override;
```

File: hoomd/mpcd/Sorter.h [hunk 30]
```diff
@@ -49,7 +49,7 @@ class PYBIND11_EXPORT Sorter : public Tuner
     virtual ~Sorter();
 
     //! Update the particle data order
-    virtual void update(uint64_t timestep);
+    virtual void update(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/Sorter.h]:
```suggestion
    void update(uint64_t timestep) override;
```

File: hoomd/mpcd/SorterGPU.h [hunk 31]
```diff
@@ -42,10 +42,10 @@ class PYBIND11_EXPORT SorterGPU : public mpcd::Sorter
     std::shared_ptr<Autotuner<1>> m_apply_tuner;
 
     //! Compute the sorting order at the current timestep on the GPU
-    virtual void computeOrder(uint64_t timestep);
+    virtual void computeOrder(uint64_t timestep) override;
```
Comment (joaander) [inline hoomd/mpcd/SorterGPU.h]:
```suggestion
    void computeOrder(uint64_t timestep) override;
```

File: hoomd/mpcd/SorterGPU.h [hunk 32]
```diff
@@ -42,10 +42,10 @@ class PYBIND11_EXPORT SorterGPU : public mpcd::Sorter
...
 
     //! Apply the sorting order on the GPU
-    virtual void applyOrder() const;
+    virtual void applyOrder() const override;
```
Comment (joaander) [inline hoomd/mpcd/SorterGPU.h]:
```suggestion
    void applyOrder() const override;
```

**Review by joaander — APPROVED** [review]
Thanks! I have one comment on style which I will apply suggestions and then merge.

**Comment by mphoward** [comment]
Thanks! I agree and have made that switch in other codes—didn’t think of it here for some reason!

**Comment by joaander** [comment]
If I get bored someday, I might add clang-tidy to hoomd's pre-commit to make these kinds of checks (and many fixes) automatic. It is working rather well in freud.
